const BASE_URL = "https://localhost:5001/api/home";

export const API_URLS = {
  gArtikli: () => `${BASE_URL}/artikli_db`,
  gArtikliDokumentJoined: () => `${BASE_URL}/joined_artikls_db`,
  gArtikliDokumentaJoinedByDate: () => `${BASE_URL}/joined_artikls_db_date_order`,
  pUpdateKolArtikl: () => `${BASE_URL}/UpdateTrenutnaKolicina`,
  pUpdateArt: (id) => `${BASE_URL}/update_artikl/${id}`,
  pAddArt: () => `${BASE_URL}/add_artikl`,
  gFifoList: (artId) => `${BASE_URL}/FIFO_list/${artId}`,
  pExecuteFifoIzdatnica: () => `${BASE_URL}/izvrsi_fifo_izdatnica`,
  gModalGraphInfo: (artId) => `${BASE_URL}/ModalGraphInfo${artId}`,
  gJoinedDokTip: () => `${BASE_URL}/joined_dokument_tip`,
  pAddDok: () => `${BASE_URL}/add_dokument`,
  gKategorije: () => `${BASE_URL}/kategorije`,
  pAddKategorija: () => `${BASE_URL}/add_kategorija`,
  pAddArtDok: () => `${BASE_URL}/add_artDok`,
  pUpdateArtDok: () => `${BASE_URL}/update_artDok`,
  gAllArtikliDokumenta: () => `${BASE_URL}/artikli_dokumenta`,
  gSingleArtikliDokumenta: (id) => `${BASE_URL}/artikli_dokumenta/${id}`,
  dDeleteArtikl: (artId) => `${BASE_URL}/delete_artikl/${artId}`,
  gJoinedNarudzbenica: () => `${BASE_URL}/joined_narudzbenice`,
  pZatvoriNarudzbenicu: () => `${BASE_URL}/zatvori_narudzbenicu`,
  gArtikliByDokument: (dokId) => `${BASE_URL}/artikli_by_dokument/${dokId}`,
  pAddNarudzbenica: () => `${BASE_URL}/add_narudzbenica`,
  gAllDobavljaciDTO: () => `${BASE_URL}/dobavljaciDTO`,
  gSingleDobavljaciDTO: (dobId) => `${BASE_URL}/dobavljaciDTO/${dobId}`,
  gAllDobavljaci: () => `${BASE_URL}/dobavljaci`,
  gSingleDobavljaci: (dobId) => `${BASE_URL}/dobavljaci/${dobId}`,
  pAddDobavljac: () => `${BASE_URL}/add_dobavljaci`,
  pUpdate_dobavljac: (dobId) => `${BASE_URL}/update_dobavljac/${dobId}`,
  dDeleteDobavljac: (dobId) => `${BASE_URL}/delete_dobavljac/${dobId}`,
  gDokumentiByDobavljac: (dobId) => `${BASE_URL}/dokumenti_by_dobavljac/${dobId}`,
  gDokumentiByDobavljacStatus: (dobId) => `${BASE_URL}/dokumenti_by_dobavljac_status/${dobId}`,
  gSkladiste: () => `${BASE_URL}/skladiste`,
  pSkladiste: () => `${BASE_URL}/skladiste`,
  pUpdateSkladiste: (sId) => `${BASE_URL}/skladiste/${sId}`,
  dObrisiDokument: (dokId) => `${BASE_URL}/obrisiDokument/${dokId}`,
  pNarudzbenicaDetalji: () => `${BASE_URL}/narudzbenica_detalji`,
  gNarudzbenicaDetalji: (dokId) => `${BASE_URL}/narudzbenica_detalji/${dokId}`,
  pNarudzbenicaRok: () => `${BASE_URL}/narudzbenica_rok`,
  gNaciniPlacanja: () => `${BASE_URL}/nacini_placanja`,
  pDodajStatusDokumenta: () => `${BASE_URL}/dodaj_status_dokumenta`,
  pUrediStatusDokumenta: () => `${BASE_URL}/uredi_status_dokumenta`,
  gStatusTipovi: () => `${BASE_URL}/statusi_tipovi`,
  gStatusiDokumenta: () => `${BASE_URL}/statusi_dokumenata`,
  pStatusiDokumenta: () => `${BASE_URL}/statusi_dokumenata`,
  gStatusiDokumentaByDok: (dokID) => `${BASE_URL}/statusi_dokumenata_by_dokument/${dokID}`,
  gDokumentStatusParovi: () => `${BASE_URL}/dokument_status_parovi`,
  pKreirajPrimNaruVezu: () => `${BASE_URL}/kreiraj_primnaru`,
  gPrimkaInfo: (dokId) => `${BASE_URL}/primka_info/${dokId}`,
  gIzdatnicaInfo: (dokId) => `${BASE_URL}/izdatnica_info/${dokId}`,
  gArtikliInfoPoPrimci: (dokId) => `${BASE_URL}/artikli_info_po_primci/${dokId}`,
  pAzurirajNarudzbenicuKolicina: () => `${BASE_URL}/azuriraj_naudzbenicu_kolicina`,
  gMonthlyStats: () => `${BASE_URL}/monthly_stats`,
  gDailyStats30Days: () => `${BASE_URL}/daily_stats_last30`,
  gDalyStats: (y,m) => `${BASE_URL}/daily_stats/${y}/${m}`,
  gMostSoldArt: () => `${BASE_URL}/most_sold_products`,
  gAvgStorageTime: () => `${BASE_URL}/average_storage_time`,


  getArtiklById: (id) => `${BASE_URL}/artikli/${id}`,



  dobavljaci: () => `${BASE_URL}/dobavljaci`,
};
