// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SKLADISTE.DAL.DataModel;

namespace SKLADISTE.DAL.Migrations
{
    [DbContext(typeof(SkladisteKresonjaDbContext))]
    [Migration("20251103210714_popravak_veza_baze")]
    partial class popravak_veza_baze
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.Arhive", b =>
                {
                    b.Property<int>("ArhivaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArhivaNaziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArhivaOznaka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumArhive")
                        .HasColumnType("datetime2");

                    b.Property<string>("Napomena")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArhivaId");

                    b.ToTable("Arhive");
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.ArhiveDokumenti", b =>
                {
                    b.Property<int>("ZapisArhivieDokumentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArhivaId")
                        .HasColumnType("int");

                    b.Property<int>("DokumentId")
                        .HasColumnType("int");

                    b.HasKey("ZapisArhivieDokumentaId");

                    b.HasIndex("ArhivaId");

                    b.HasIndex("DokumentId");

                    b.ToTable("ArhiveDokumenti");
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.ArhiveStanja", b =>
                {
                    b.Property<int>("ZapisArhiveStanjaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArhivaId")
                        .HasColumnType("int");

                    b.Property<int?>("ArhivaId1")
                        .HasColumnType("int");

                    b.Property<int>("ArtiklId")
                        .HasColumnType("int");

                    b.Property<int?>("ArtiklId1")
                        .HasColumnType("int");

                    b.Property<int>("ArtiklKolicina")
                        .HasColumnType("int");

                    b.HasKey("ZapisArhiveStanjaId");

                    b.HasIndex("ArhivaId");

                    b.HasIndex("ArhivaId1");

                    b.HasIndex("ArtiklId");

                    b.HasIndex("ArtiklId1");

                    b.ToTable("ArhiveStanja");
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.Artikl", b =>
                {
                    b.Property<int>("ArtiklId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArtiklJmj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArtiklNaziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArtiklOznaka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KategorijaId")
                        .HasColumnType("int");

                    b.HasKey("ArtiklId");

                    b.HasIndex("KategorijaId");

                    b.ToTable("Artikli");
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.ArtikliDokumenata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtiklId")
                        .HasColumnType("int");

                    b.Property<float>("Cijena")
                        .HasColumnType("real");

                    b.Property<int>("DokumentId")
                        .HasColumnType("int");

                    b.Property<float>("Kolicina")
                        .HasColumnType("real");

                    b.Property<int>("RbArtikla")
                        .HasColumnType("int");

                    b.Property<int>("TrenutnaKolicina")
                        .HasColumnType("int");

                    b.Property<float>("UkupnaCijena")
                        .HasColumnType("real");

                    b.Property<string>("ZaposlenikId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtiklId");

                    b.HasIndex("DokumentId");

                    b.ToTable("ArtikliDokumenata");
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.Dobavljac", b =>
                {
                    b.Property<int>("DobavljacId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdresaDobavljaca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DobavljacNaziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("brojTelefona")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DobavljacId");

                    b.ToTable("Dobavljaci");
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.Dokument", b =>
                {
                    b.Property<int>("DokumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Arhiviran")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DatumDokumenta")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DobavljacId")
                        .HasColumnType("int");

                    b.Property<string>("Dostavio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MjestoTroska")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Napomena")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("OznakaDokumenta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipDokumentaId")
                        .HasColumnType("int");

                    b.Property<string>("ZaposlenikId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DokumentId");

                    b.HasIndex("DobavljacId");

                    b.HasIndex("TipDokumentaId");

                    b.ToTable("Dokumenti");
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.DokumentByArhivaId", b =>
                {
                    b.Property<int>("ArhivaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumDokumenta")
                        .HasColumnType("datetime2");

                    b.Property<int>("DokumentId")
                        .HasColumnType("int");

                    b.Property<string>("OznakaDokumenta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipDokumenta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZaposlenikId")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("DokumentByArhivaId");
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.DokumentTip", b =>
                {
                    b.Property<int>("TipDokumentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TipDokumenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipDokumentaId");

                    b.ToTable("DokumentTipovi");
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.Kategorija", b =>
                {
                    b.Property<int>("KategorijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KategorijaNaziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KategorijaNaziv2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KategorijaId");

                    b.ToTable("Kategorije");
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.LokacijeArtikala", b =>
                {
                    b.Property<int>("LOK_ART_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ART_DOK_ID")
                        .HasColumnType("int");

                    b.Property<int>("LOK_ID")
                        .HasColumnType("int");

                    b.Property<int>("red")
                        .HasColumnType("int");

                    b.Property<int>("stupac")
                        .HasColumnType("int");

                    b.HasKey("LOK_ART_ID");

                    b.HasIndex("ART_DOK_ID");

                    b.HasIndex("LOK_ID");

                    b.ToTable("LokacijeArtikala");
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.Nacin_Placanja", b =>
                {
                    b.Property<int>("NP_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NP_Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NP_Id");

                    b.ToTable("NaciniPlacanja");
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.NarudzbenicaDetalji", b =>
                {
                    b.Property<int>("DokumentId")
                        .HasColumnType("int");

                    b.Property<string>("MjestoIsporuke")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NP_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("RokIsporuke")
                        .HasColumnType("datetime2");

                    b.HasKey("DokumentId");

                    b.HasIndex("NP_Id");

                    b.ToTable("NarudzbenicaDetalji");
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.PrimNaruVeze", b =>
                {
                    b.Property<int>("PmvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NarudzbenicaId")
                        .HasColumnType("int");

                    b.Property<int>("PrimkaId")
                        .HasColumnType("int");

                    b.HasKey("PmvId");

                    b.HasIndex("NarudzbenicaId");

                    b.HasIndex("PrimkaId");

                    b.ToTable("PrimNaruVeze");
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.SkladisteLokacija", b =>
                {
                    b.Property<int>("LOK_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BR_RED")
                        .HasColumnType("int");

                    b.Property<int>("BR_STUP")
                        .HasColumnType("int");

                    b.Property<bool>("NEMA_MJESTA")
                        .HasColumnType("bit");

                    b.Property<string>("POLICA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("skladiste_id")
                        .HasColumnType("int");

                    b.HasKey("LOK_ID");

                    b.HasIndex("skladiste_id");

                    b.ToTable("SkladisteLokacija");
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.SkladistePodatci", b =>
                {
                    b.Property<int>("SkladisteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdresaSkladista")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkladisteNaziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("brojTelefona")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkladisteId");

                    b.ToTable("SkladistePodatcis");
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.StatusDokumenta", b =>
                {
                    b.Property<int>("DokumentId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZaposlenikId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("aktivan")
                        .HasColumnType("bit");

                    b.HasKey("DokumentId", "StatusId");

                    b.HasIndex("StatusId");

                    b.ToTable("StatusiDokumenata");
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.StatusTip", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StatusNaziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("StatusId");

                    b.ToTable("StatusiTipova");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SKLADISTE.DAL.DataModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SKLADISTE.DAL.DataModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SKLADISTE.DAL.DataModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SKLADISTE.DAL.DataModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.ArhiveDokumenti", b =>
                {
                    b.HasOne("SKLADISTE.DAL.DataModel.Arhive", "Arhiva")
                        .WithMany("ArhiveDokumenti")
                        .HasForeignKey("ArhivaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SKLADISTE.DAL.DataModel.Dokument", "Dokument")
                        .WithMany("ArhiveDokumenti")
                        .HasForeignKey("DokumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.ArhiveStanja", b =>
                {
                    b.HasOne("SKLADISTE.DAL.DataModel.Arhive", null)
                        .WithMany()
                        .HasForeignKey("ArhivaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SKLADISTE.DAL.DataModel.Arhive", "Arhiva")
                        .WithMany("ArhiveStanja")
                        .HasForeignKey("ArhivaId1");

                    b.HasOne("SKLADISTE.DAL.DataModel.Artikl", null)
                        .WithMany()
                        .HasForeignKey("ArtiklId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SKLADISTE.DAL.DataModel.Artikl", "Artikl")
                        .WithMany("ArhiveStanja")
                        .HasForeignKey("ArtiklId1");
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.Artikl", b =>
                {
                    b.HasOne("SKLADISTE.DAL.DataModel.Kategorija", "Kategorija")
                        .WithMany()
                        .HasForeignKey("KategorijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.ArtikliDokumenata", b =>
                {
                    b.HasOne("SKLADISTE.DAL.DataModel.Artikl", "Artikl")
                        .WithMany()
                        .HasForeignKey("ArtiklId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SKLADISTE.DAL.DataModel.Dokument", "Dokument")
                        .WithMany("ArtikliDokumenata")
                        .HasForeignKey("DokumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.Dokument", b =>
                {
                    b.HasOne("SKLADISTE.DAL.DataModel.Dobavljac", null)
                        .WithMany("Dokumenti")
                        .HasForeignKey("DobavljacId");

                    b.HasOne("SKLADISTE.DAL.DataModel.DokumentTip", "TipDokumenta")
                        .WithMany("Dokumenti")
                        .HasForeignKey("TipDokumentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.LokacijeArtikala", b =>
                {
                    b.HasOne("SKLADISTE.DAL.DataModel.ArtikliDokumenata", "ArtikliDokument")
                        .WithMany("LokacijeArtikala")
                        .HasForeignKey("ART_DOK_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SKLADISTE.DAL.DataModel.SkladisteLokacija", "Lokacija")
                        .WithMany("LokacijeArtikala")
                        .HasForeignKey("LOK_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.NarudzbenicaDetalji", b =>
                {
                    b.HasOne("SKLADISTE.DAL.DataModel.Dokument", null)
                        .WithOne()
                        .HasForeignKey("SKLADISTE.DAL.DataModel.NarudzbenicaDetalji", "DokumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SKLADISTE.DAL.DataModel.Nacin_Placanja", "NacinPlacanja")
                        .WithMany("Narudzbenice")
                        .HasForeignKey("NP_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.PrimNaruVeze", b =>
                {
                    b.HasOne("SKLADISTE.DAL.DataModel.Dokument", "Narudzbenica")
                        .WithMany("NarudzbeniceVeze")
                        .HasForeignKey("NarudzbenicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SKLADISTE.DAL.DataModel.Dokument", "Primka")
                        .WithMany("PrimkeVeze")
                        .HasForeignKey("PrimkaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.SkladisteLokacija", b =>
                {
                    b.HasOne("SKLADISTE.DAL.DataModel.SkladistePodatci", "Skladiste")
                        .WithMany("Lokacije")
                        .HasForeignKey("skladiste_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SKLADISTE.DAL.DataModel.StatusDokumenta", b =>
                {
                    b.HasOne("SKLADISTE.DAL.DataModel.Dokument", "Dokument")
                        .WithMany("StatusDokumenta")
                        .HasForeignKey("DokumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SKLADISTE.DAL.DataModel.StatusTip", "StatusTip")
                        .WithMany("StatusiDokumenata")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
